### ISSUE TITLE
[Ask] your opinion about function time() 

### ISSUE THREAD

**Issue by k2biru** [SensorsIot/NTP-time-for-ESP8266-and-ESP32#2]
Sorry if i ask in wrong place and wrong person.

## ASK about function time(time_t)

If function `time()` on (arduino core) `time.cpp` always call SNTP (need internet connection), then ESP8266 doesn't have any internal clock?
if that so, should i count it manually?

or function `sntp_get_current_timestamp();` inside `time();` only sync current time. (not always call SNTP)

```
time_t time(time_t * t)
{
    time_t seconds = sntp_get_current_timestamp();
    if (t)
    {
        *t = seconds;
    }
    return seconds;
}
```

**Comment by SensorsIot** [comment]
The ESPs have an internal clock for millis(). It is not very precise. The time() function calls the ntp server every hour and between keeps the time up-to-date using the internal "clock"
