### ISSUE TITLE
showTime() contains some subtle bugs

### ISSUE THREAD

**Issue by Paraphraser** [SensorsIot/NTP-time-for-ESP8266-and-ESP32#3]
In NTP_Example.ino, line 159 reads:

```
if (localTime->tm_mday = 0) localTime->tm_mday = 7;
```

I think this contains two distinct bugs:

* It references *tm_mday* (day of month) instead of *tm_wday* (day of week); and
* It performs an unconditional assignment of zero to *tm_mday* (that all-too-common C problem of the difference between "=" and "==" and the compiler letting you get away with it).

I think it more likely that you intended to write:

```
if (localTime->tm_wday == 0) localTime->tm_wday = 7;
```

The effect of the code as-written is:

1. The subsequent *print()* statement will only ever show day-of-week values in the range 0..6; and
2. The day-of-month will always be zero after this line is executed.

Only [1] will have any effect in this sketch as-written because *timeinfo* is updated by *getNTPtime()* every loop before *showtime()* is called and no other use is made of *timeinfo* after *showtime()*. But it could become a problem if *timeinfo* were re-used.

In general, I try my best to treat structures like *tm* as read-only. Also, the likelihood of an unwanted side-effect of a bug being propagated outside of the function containing the bug could be minimised by passing a _copy_ of the *tm* structure rather than a _pointer_ to the *tm* structure:

Something like:

```
void showTime(tm localTime) {
    Serial.printf(
        "%04d-%02d-%02d %02d:%02d:%02d, day %d, %s time\n",
        localTime.tm_year + 1900,
        localTime.tm_mon + 1,
        localTime.tm_mday,
        localTime.tm_hour,
        localTime.tm_min,
        localTime.tm_sec,
        (localTime.tm_wday > 0 ? localTime.tm_wday : 7 ),
        (localTime.tm_isdst == 1 ? "summer" : "standard")
    );
}

...
   showtime(timeinfo);
...
```

**Comment by SensorsIot** [comment]
Thank you! I implemented the correction and added your way of printing as a second possibility.
