### ISSUE TITLE
project help

### ISSUE THREAD

**Issue by yo2ldk** [SensorsIot/NTP-time-for-ESP8266-and-ESP32#5]
Hallo Andreas,

  I see your projects and I learn a lot, even if I'm over 50;s  :)
   sorry for issue here, but not have any email of you
   what I need is a way to get some info spots from web, to an esp32 and see it on  lcd display in a text box
   need to be a kind of format or haw can i get it?
   tnx in advance !
   edit:
    sory I see some time ago on youtube ham radio related and I found now your callsign..
to be more specific and now I know you understand what  I need, is to get DX spots via wifi with an esp and to read it on lcd
I search some projects but not find so, you will be first.
I try it but my skills is just at beginning...
my best regards, 
                                de yo2ldk

**Comment by SensorsIot** [comment]
Hi,
YouTube is only my hobby and I share my know-how in my videos. I am sure you will find what you need if you divide your project into parts. For each part, you will find help on Google and maybe even in my videos.
Good luck and enjoy the journey.
73 de Andreas, HB9BLA
