### ISSUE TITLE
Thank you for something that works.

### ISSUE THREAD

**Issue by donwade** [SensorsIot/NTP-time-for-ESP8266-and-ESP32#6]
Well I snagged some 3 liners from github on how to retrieve NTP time on an esp32, 
Three lines. It all worked fine for months.
Then my program stopped working, no NTP time. 
I went back to the simple examples, they all failed too. 

I found your code and yours is the only version that works with the "retry" logic.
Three days of searching for a working example.

Thanks for your code.

**Comment by SensorsIot** [comment]
I am glad this old stuff still is helpful. Thanks for your feedback!
